### ISSUE TITLE
Build fails with "Maximum call stack size exceeded" when "concatenateModules" and "webpack-remove-empty-scripts" is enabled

### ISSUE THREAD

**Issue by galeo** [webdiscus/webpack-remove-empty-scripts#1]
This is a continuation of the discussion from webpack/webpack#12068.

We have met the same problem. Hope to see this issue could be fixed. Thanks so much.

**Comment by webdiscus** [comment]
@galeo Thank you for reporting the problem, I'll take care of it.

**Comment by webdiscus** [comment]
Hello @galeo,

I have fixed the issue. The problem was by usage  redux package, that has too mach dependency imports. By this case, sometime, the Webpack inner generates a structure different from the 'standard' of dependency module that the plugin does not expect. This problem was fixed. 

Update please your package.json to version 0.6.4.
https://www.npmjs.com/package/webpack-remove-empty-scripts/v/0.6.4

P.S. can you please test this fix by your project and tell me a result.
Thanks,
Dmitirj

**Comment by kuworking** [comment]
@webdiscus In my setup it does work, a thousand thanks

**Comment by galeo** [comment]
@webdiscus I can confirm it works well. Thanks a lot.

**Comment by galeo** [comment]
@webdiscus  Sorry, I have to reopen this issue. 

> The problem was by usage redux package, that has too mach dependency imports. By this case, sometime, the Webpack inner generates a structure different from the 'standard' of dependency module that the plugin does not expect.

This error would also occur when try to import jQuery in files. May be the same as above?

**Comment by webdiscus** [comment]
> @webdiscus Sorry, I have to reopen this issue.
> 
> > The problem was by usage redux package, that has too mach dependency imports. By this case, sometime, the Webpack inner generates a structure different from the 'standard' of dependency module that the plugin does not expect.
> 
> This error would also occur when try to import jQuery in files. May be the same as above?

@galeo Thank you for your issue report! It is very important for more people.

I can't reproduce a issue by import of jQuery. See my simpelst code:
### package.json 
```
..
"jquery": "^3.5.1",
..
```

### webpack.config.js
```
..
entry: { 'app': path.join(__dirname, 'app.js' }
optimization: {
      concatenateModules: true,
}
..
```

###  jquery-test.js 
```
import jQuery from 'jquery';
const jq = require('jquery')(window);

export default function jqueryTest (str) {
    jQuery('.element').text(str);
    jq('.element').text(str);
}
```

### app.js
```
import jqueryTest from './jquery-test';
jqueryTest('Hello world!')
```

P.S. can you please send me a code sample with you can reproduce the issue?

**Comment by galeo** [comment]
To include jQuery from a CDN instead of bundling it. We config the `externals` option in `webpack.config.js`:
```
module.exports = {
  //...
  externals: {
    jquery: 'jQuery'
  },
  //...
};
```
In this case this error would occur. You can have a try. Thanks.

**Comment by webdiscus** [comment]
> To include jQuery from a CDN instead of bundling it. We config the `externals` option in `webpack.config.js`:
> 
> ```
> module.exports = {
>   //...
>   externals: {
>     jquery: 'jQuery'
>   },
>   //...
> };
> ```
> 
> In this case this error would occur. You can have a try. Thanks.

Thank you @galeo! 
In your case was generated by Webpack yet one different unexpected structure of dependency object. I have implement a general solution independently to a structure.

Please update your package to version 0.7.0 and tell me a result. Thanks.

**Comment by galeo** [comment]
This time it works correctly. Thanks so much.
