### ISSUE TITLE
[BUG] removed empty file still processed by other plugins

### ISSUE THREAD

**Issue by xoxys** [webdiscus/webpack-remove-empty-scripts#10]
**Describe the bug**
After upgrading to `webpack-remove-empty-scripts` v0.8.2 I'm facing this issue:

```
[webpack-cli] Error: ENOENT: no such file or directory, open 'static/js/css-06f62c46.bundle.min.js'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at fileSum (/home/myuser/Devel/private/hugo/hugo-geekdoc/webpack.plugins.js:40:56)
    at calculateSRI (/home/myuser/Devel/private/hugo/hugo-geekdoc/webpack.plugins.js:42:25)
    at /home/myuser/Devel/private/hugo/hugo-geekdoc/webpack.plugins.js:46:29
    at Array.forEach (<anonymous>)
    at /home/myuser/Devel/private/hugo/hugo-geekdoc/webpack.plugins.js:44:25
    at Hook.eval [as callAsync] (eval at create (/home/myuser/Devel/private/hugo/hugo-geekdoc/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/myuser/Devel/private/hugo/hugo-geekdoc/node_modules/tapable/lib/Hook.js:18:14)
    at /home/myuser/Devel/private/hugo/hugo-geekdoc/node_modules/webpack/lib/Compiler.js:498:23 {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: 'static/js/css-06f62c46.bundle.min.js'
}
```

The `static/js/css-06f62c46.bundle.min.js` file is an empty js file created by a scss only entry in the webpack config:

```
  entry: {
    css: [
      path.resolve("src", "sass", "main.scss"),
      path.resolve("src", "sass", "mobile.scss"),
      path.resolve("src", "sass", "print.scss")
    ],
```

While everything was working as expected in v0.8.1 something has changed in v0.8.2+. Other plugins, In my case webpack-manifest-plugin, seems to be able to still see those empty scripts and try to process them even if `webpack-remove-empty-scripts` has successfully removed them, so this might be some kind of race condition. Looks like that's related to https://github.com/webdiscus/webpack-remove-empty-scripts/commit/0a5ec81e685074d354342c3bfb6c7ce63cdb1467. Any chance to get it fixed?

**Comment by webdiscus** [comment]
@xoxys Hallo Robert,

thanks for bug report.
Can you please create small repo with reproducible issue.

Yes, in v0.8.2 the stage of deleting an empty file has been changed to fix issue with one Plugin that require all generated files.

**Before v0.8.2:** empty scripts are deleted at asset compilation. All other plugins will be called after empty scripts are deleted.

**After v0.8.2:** empty scripts are removed after all plugins have been processed. That was the solution for the issue #9.

Now we have a vicious circle:
one plugin needs all generated files and the other vice versa.
What can I do?
I have an idea. I can add an option e.g. `stage` - when should the files be deleted: before or after plugin processing.

What should then be by default: `before` or `after`?
I think `before` should be default, like in v0.8.1.

Viele Grüße,
Dimitri

**Comment by xoxys** [comment]
Thanks for your fast reply. I like the idea to introduce a stage option. Im fine with whatever default you chose, but yeah restoring the initial behavior might make sense. Do you still need a reproducible repo?

**Comment by webdiscus** [comment]
>  Do you still need a reproducible repo?

I have never used the `webpack-manifest-plugin` and I don't know how is the plugin in your _webpack.config.js_ configured.
Firstly would be nice, if you share here your config and I try create a test case to reproduce the issue.

**Comment by xoxys** [comment]
No Problem. Here is my config https://github.com/thegeeklab/hugo-geekdoc/blob/main/webpack.config.js

I can also create a minimal repo if thats easier.

**Comment by webdiscus** [comment]
@xoxys 

I have cloned your [hugo-geekdoc](https://github.com/thegeeklab/hugo-geekdoc) repo with v0.8.4.
With `npm start` I can reproduce the issue.

**Comment by xoxys** [comment]
I've added a temp fix a few hours ago, so you might need to checkout an older commit, e.g. https://github.com/thegeeklab/hugo-geekdoc/commit/71179798e40b85bf97d24401fd046b540d82ca7a.

Besides that `npm run start:webpack` is required (or webpack in development mode):

```
❯ git clone https://github.com/thegeeklab/hugo-geekdoc
Klone nach 'hugo-geekdoc'...
[...]
myuser@superion ~/.tmp took 4s 
❯ cd hugo-geekdoc/
myuser@superion hugo-geekdoc on  main is 📦 v1.0.0 via  v16.15.0 
❯ git checkout 71179798e40b85bf97d24401fd046b540d82ca7a
[...]
HEAD ist jetzt bei 7117979 chore(deps): lock file maintenance (#493)
myuser@superion hugo-geekdoc on  HEAD (7117979) is 📦 v1.0.0 via  v16.15.0 
❯ npm install

added 1102 packages, and audited 1103 packages in 17s

16 vulnerabilities (5 moderate, 10 high, 1 critical)

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
myuser@superion hugo-geekdoc on  HEAD (7117979) is 📦 v1.0.0 via  v16.15.0 took 16s 
❯ npm run start:webpack

> geekdoc@1.0.0 start:webpack
> webpack --mode=development --watch

[webpack-cli] Error: ENOENT: no such file or directory, open 'static/js/css-06f62c46.bundle.min.js'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at fileSum (/home/myuser/.tmp/hugo-geekdoc/webpack.plugins.js:40:56)
    at calculateSRI (/home/myuser/.tmp/hugo-geekdoc/webpack.plugins.js:42:25)
    at /home/myuser/.tmp/hugo-geekdoc/webpack.plugins.js:46:29
    at Array.forEach (<anonymous>)
    at /home/myuser/.tmp/hugo-geekdoc/webpack.plugins.js:44:25
    at Hook.eval [as callAsync] (eval at create (/home/myuser/.tmp/hugo-geekdoc/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/myuser/.tmp/hugo-geekdoc/node_modules/tapable/lib/Hook.js:18:14)
    at Watching._done (/home/myuser/.tmp/hugo-geekdoc/node_modules/webpack/lib/Watching.js:287:28) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: 'static/js/css-06f62c46.bundle.min.js'
}
```

**Comment by webdiscus** [comment]
@xoxys I known, you have it fixed.

I can reproduce the issue with:
```js
 new WebpackManifestPlugin({
      fileName: "../data/assets.json",
      publicPath: "",
      writeToFileEmit: true,
      generate(seed, files) {
        let manifest = {}

        files.forEach(function (element, index) {
          if (element.name.endsWith(".svg")) return

          Object.assign(manifest, {
            [element.name]: { src: element.path }
          })
        })

        return manifest
      }
    }),
```

**Comment by webdiscus** [comment]
@xoxys 

I have new v1.0.0 released. In this version was reverted defaults behaviour as in `v0.8.1` - remove empty scripts before other plugins will be called.

Added new `stage` option with following values:

- `RemoveEmptyScriptsPlugin.STAGE_BEFORE_PROCESS_PLUGINS` (default)\
  Remove empty scripts `before` processing other plugins.\
  For example, exact this stage needs for properly work of the `webpack-manifest-plugin`.
- `RemoveEmptyScriptsPlugin.STAGE_AFTER_PROCESS_PLUGINS`\
  Remove empty scripts `after` processing all other plugins.\
  For example, exact this stage needs for properly work of the `@wordpress/dependency-extraction-webpack-plugin`.

**Comment by xoxys** [comment]
Yeah, can confirm that it works again as expected. Thanks a lot for the fast fix :+1:

**Comment by xoxys** [comment]
Please feel free to close the issue whenever you like.
