### ISSUE TITLE
doesn't work in rspack

### ISSUE THREAD

**Issue by exocornet** [webdiscus/webpack-remove-empty-scripts#15]
Hello. This plugin does not work in rspack. I wrote a temporary solution as a function, but I would like to include your webpack-remove-empty-scripts plugin in rspack.

https://github.com/exocornet/express-template

**Comment by webdiscus** [comment]
Hello @exocornet,

thanks for the issue report.
Can you please create a small repo using `rspack` with reproducible issue?

Thanks!

**Comment by webdiscus** [comment]
@exocornet 

I tried to create simple test using latest version of `rspack@0.7.5` and `mini-css-extract-plugin@2.9.0`.

The simple `rspack.config.js`:

```js
const path = require('path');
const MiniCssExtractPlugin = require('mini-css-extract-plugin');
const RemoveEmptyScriptsPlugin = require('webpack-remove-empty-scripts');

module.exports = {
  output: {
    path: path.join(__dirname, 'dist/'),
    publicPath: '',
  },

  entry: {
    'styles': './src/styles.css',
  },

  plugins: [
    new RemoveEmptyScriptsPlugin(),
    new MiniCssExtractPlugin(),
  ],

  module: {
    rules: [
      {
        test: /\.css$/,
        use: [
          MiniCssExtractPlugin.loader,
          'css-loader',
        ]
      },
    ]
  },
};
```

The script in package.json:
```js
 ...
  "scripts": {
    "build": "NODE_ENV=production rspack build"
  },
  ...
```

Run build:
```
npm run build
```

Error:
```
> rspack-remove-empty-scripts@1.0.0 build
> NODE_ENV=production rspack build

TypeError: Cannot read properties of undefined (reading 'registerLoader')
at MiniCssExtractPlugin.apply (/Users/xxx/rspack-issue/node_modules/mini-css-extract-plugin/dist/index.js:578:34)
at createCompiler (/Users/xxx/rspack-issue/node_modules/@rspack/core/dist/rspack.js:54:24)
at create (/Users/xxx/rspack-issue/node_modules/@rspack/core/dist/rspack.js:89:26)
at rspack (/Users/xxx/rspack-issue/node_modules/@rspack/core/dist/rspack.js:115:37)
at RspackCLI.createCompiler (/Users/xxx/rspack-issue/node_modules/@rspack/cli/dist/rspack-cli.js:66:34)
at async Object.handler (/Users/xxx/rspack-issue/node_modules/@rspack/cli/dist/commands/build.js:105:30)
```

Firstly, the `mini-css-extract-plugin` in rspack must work, because the `webpack-remove-empty-scripts` works only with `mini-css-extract-plugin`.

**Comment by exocornet** [comment]
Hello. Here is my repository for reproducing the error.
https://github.com/exocornet/express-template-remove-empty-js

Configuration file rspack 
https://github.com/exocornet/express-template-remove-empty-js/blob/main/rspack.config.js

I'm using a plugin (line:7)
CssExtractRspackPlugin 

I temporarily wrote a script, but during local development it does not delete empty script files. If you run the npm start command and go to the path http://localhost:8000/js/Footer.js, you will see an empty file. (line 12) 
You will see an empty file with the answer 200. If your plugin can be adapted for rspack or somehow my code will help you, it will be cool. Thank you.

I also asked the creators of rspack and they gave this answer.
https://github.com/web-infra-dev/rspack/issues/6644#issuecomment-2162077044

> The plugin's relying on a few hooks that does quite expensive jobs on the JS side. We're not likely to support this.
> https://github.com/webdiscus/webpack-remove-empty-scripts/blob/84157f850976c00474a97cc954f2a9837c2c0347/src/index.js#L53-L102

**Comment by webdiscus** [comment]
@exocornet 

thank you for the repo, now I can reproduce the issue using RSPack.
I try to fixt it or perhaps create a separate version for RSPack.

**Comment by webdiscus** [comment]
@exocornet 

the RSPack is absolutely not compatible with the Webpack. The inner structure of `compilation` is other.
RSpack doesn't have the `moduleGraph`. This is the basis of the functionality this plugin. Without `moduleGraph` the `webpack-remove-empty-scripts` cannot work.

Sorry, for the RSPack should be created another plugin. I don't know RSPack and can't make a plugin for it.

**Comment by webdiscus** [comment]
why by the `compilation.hooks.processAssets` the argument `assets` is empty object? There should be the list of objects.
I don't understand how works RSPack. Currently RSPack is unusable. I can see RSPack after the release any `1.x` version, it’s still early
