### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by lmcsu** [webdiscus/webpack-remove-empty-scripts#7]
Doesn't work with TS

```
import RemoveEmptyScriptsPlugin from 'webpack-remove-empty-scripts';
```

> TS7016: Could not find a declaration file for module 'webpack-remove-empty-scripts'. '.../node_modules/webpack-remove-empty-scripts/src/index.js' implicitly has an 'any' type.

**Comment by webdiscus** [comment]
@lmcsu 

The `webpack-remove-empty-scripts` is the Webpack plugin and should be used in Webpack config with CommonJS syntax:

```js
const RemoveEmptyScriptsPlugin = require('webpack-remove-empty-scripts');

module.exports = {
  //...
  plugins: [
    new RemoveEmptyScriptsPlugin(),
    //...
  ],
};
```

I don't know your usage case.
Can you please create a small repo?

**Comment by lmcsu** [comment]
@webdiscus who said that webpack configs must be written only in js/cjs?

https://webpack.js.org/configuration/configuration-languages/#typescript

**Comment by webdiscus** [comment]
@lmcsu 

I have never used TS.
Can you please create a small repo with your usage case?

**Comment by lmcsu** [comment]
@webdiscus providing a repo won't help much. The issue is that this plugin doesn't have TS support. But almost all other pluguns have. And TS configs are supported by Webpack natively. You must at least include some d.ts file into the repo to make it TS compatible.
