### ISSUE TITLE
webpack-remove-empty-scripts is removing asset.php files

### ISSUE THREAD

**Issue by tstokes8040** [webdiscus/webpack-remove-empty-scripts#9]
**Describe the bug**
The build process is running @WordPress/Scripts. This will also output an asset.php file for each CSS file generated.

I want to use that plugin to remove the .JS files that get created with the compiled CSS files. These .JS files are empty and just annoying to have in there.

When using the plugin it is also removing my asset.php files as well. I have tried the options including ignoring asset.php files but it still doesn't work.

Any ideas? Below is the code I have:

```
const otherStyleConfig = {
    ...defaultConfig,
    entry: {
        'blog': path.resolve( './src/sass', 'blog.scss' ),
    },
    module: {
        rules: [
        {
            test: /\.scss$/,
            exclude: /node_modules/,
            use: [
                MiniCssExtractPlugin.loader,
                {
                    loader: "css-loader",
                    options: {
                        url: false, //Don't do anything with image url's
                    },
                },
                {
                    loader: "postcss-loader",
                    options: {
                        postcssOptions: {
                            plugins: [
                                sortMediaQueries(),
                                presetEnv(),
                                mergeLonghand(),
                                mergeRules(),
                                cssnano( {
                                    reduceIdents: false,
                                    zindex: false,
                                    autoprefixer: false,
                                } ),
                            ],
                            options: {},
                        },
                     },
                },
                'resolve-url-loader',
                'sass-loader',
            ],
        },
        ],
    },
    output: {
        path: path.resolve(__dirname, 'build/css'),
    },
    devtool: 'source-map',
    plugins: [
        new MiniCssExtractPlugin(),
        new DependencyExtractionWebpackPlugin(),
        new RemoveEmptyScriptsPlugin({
            verbose: true,
            ignore: [
                /.*asset.php$/,
            ]
        }),
    ]
}
```

**To Reproduce**
1. Create a simple SASS compile in Webpack config like the example above.
2. Use @WordPress/Scripts for the build process. This should be in your package.json file `"build": "wp-scripts build --mode=production",`
3. You will see the empty .js files are no longer there but the asset.php files are not there either. If you remove the plugin from the Webpack config you will see that the asset.php files are there and the empty .js files.

**Expected behavior**
To just remove the empty JS files and not asset.php files

**Dev Environment (please complete the following information):**
 - OS: MacOS
 - Node: v14.17.0

**Comment by webdiscus** [comment]
Hello Tyler,

this is an interesting use case.
Could you please create a small repo (docker-compose) with a reproducible issue? Then I can start fixing it.

Thx,
Dimitrij

**Comment by tstokes8040** [comment]
@webdiscus Can I just provide you with a small repo? I think docker is overkill here.

**Comment by webdiscus** [comment]
> @webdiscus Can I just provide you with a small repo? I think docker is overkill here.

yes, of cause a repo is enough. I have macOS, M1.

**Comment by tstokes8040** [comment]
@webdiscus Here is the test repo for you:

https://github.com/tstokes8040/remove-empty-scripts-test

Please let me know if you have any questions.

**Comment by webdiscus** [comment]
@tstokes8040 

I found the problem. It is difficult to around.
When is deleted empty `main.js` asset via Webpack API `compilation.deleteAsset(file)`, then the DependencyExtractionWebpackPlugin don't create the `main.asset.php` file in `build/css/`.

P.S.: I have an idea, but I need time to test and not break everything that already works ;-)

**Comment by webdiscus** [comment]
@tstokes8040,
I have fixed the issue. Try please v0.8.3.

**Comment by tstokes8040** [comment]
@webdiscus NICE WORK! Thank you SO much for this update. This is amazing!!!! It works great! I will go ahead and close out this bug. Thanks again!

**Comment by webdiscus** [comment]
@tstokes8040 

By fixing this issue was broken compatibility with vast majority other plugins, e.g. issue #10
Therefore I have new v1.0.0 released. 
In this version was reverted defaults behaviour as in `v0.8.1` - remove empty scripts before other plugins will be called.

To fix your issue is added new `stage` option with following values:

- `RemoveEmptyScriptsPlugin.STAGE_BEFORE_PROCESS_PLUGINS` (default)\
  Remove empty scripts `before` processing other plugins.\
  For example, exact this stage needs for properly work of the `webpack-manifest-plugin`.
- `RemoveEmptyScriptsPlugin.STAGE_AFTER_PROCESS_PLUGINS`\
  Remove empty scripts `after` processing all other plugins.\
  For example, exact this stage needs for properly work of the `@wordpress/dependency-extraction-webpack-plugin`.

If you update to `v1.0.0` then add the `stage` option as following:

```js
new RemoveEmptyScriptsPlugin({
    stage: RemoveEmptyScriptsPlugin.STAGE_AFTER_PROCESS_PLUGINS, // <- use this option
}),
```

**Comment by tstokes8040** [comment]
@webdiscus Thanks so much! I've got this updated!!
